filebeat.prospectors:
- type: log
  paths:
    - /var/log/*.log
  scan_frequency: 1s
  document_type: json
  json.message_key: log
  json.keys_under_root: true
  json.overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]