filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log
  scan_frequency: 1s

setup.kibana:
  host: "kibana:5601"

filebeat.config.modules:
  path: /filebeat/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

setup.template.settings:
  index.number_of_shards: 3