version: "2"
services:
  php:
    image: php:7.2-apache
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./php/html:/var/www/html/
      - ./log-apache:/var/log
  elasticsearch:
    image: elasticsearch:6.5.1
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:6.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:6.5.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
    depends_on:
      - elasticsearch
  filebeat-app:
    image: docker.elastic.co/beats/filebeat:6.5.1
    volumes:
      - ./filebeat-app/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log-app:/var/log:ro
    depends_on:
      - logstash
  filebeat-php:
    image: docker.elastic.co/beats/filebeat:6.5.1
    volumes:
      - ./filebeat-php/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log-apache:/var/log:ro
    depends_on:
      - logstash
  application:
    image: edupaim/golang-app-test-elk-beat
    ports:
      - "9331:9331"
    volumes:
      - ./log-app:/app/log
volumes:
  logpath: